[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "npm install -g pnpm",
  "pnpm install"
]

[phases.build]
cmds = [
  "pnpm -r build"
]

[start]
cmd = "cd server && node dist/index.js"
